version: '3.9'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./www:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - ./www:/var/www
      - ./nginx:/etc/nginx/conf.d

  #MySQL Service
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ./mysql_data:/var/lib/mysql

#Docker Networks
networks:
  app-network:
    driver: bridge
